spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Czh2000.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver